services:
  neox-consensus:
    build: .
    container_name: neox-consensus
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./node-data:/data
    environment:
      - EXTERNAL_IP=0.0.0.0

